### ISSUE TITLE
How many new homepages are there?

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/website#1]
How does this work relate to https://github.com/citizenlabsgr/website?

**Comment by BrandonKlotz** [comment]
Yeah I think that is the failed Hacktoberfest redesign attempt. I liked the repo name homepage but was taken. We can delete the /website repo

**Comment by Allen616** [comment]
Going to close this one out. I think we understand where things are going now.

**Comment by jacebrowning** [comment]
![](https://memegen.link/custom/the_homepages_are_easily_scared/but_they'll_be_back,_and_in_greater_numbers.jpg?alt=http://img.playbuzz.com/image/upload/f_auto,fl_lossy,q_auto/cdn/7c9b66e1-91af-4b51-8ab5-f76f5eba7e30/e48f149b-708c-47a9-8f40-2e48881447da.jpg)

**Comment by BrandonKlotz** [comment]
Website should go away 😂
