### ISSUE TITLE
List featured projects on the homepage

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/website#37]
@Allen616 Which file controls the homepage content?

**Comment by Allen616** [comment]
Man, this is old... my bad.

I have updated the documentation with the readme.md and contributing.md. Much of the homepage content is controlled by the config.toml file. Changes are made locally, when the website is rendered.

**Comment by Allen616** [comment]
Each project would have a specific markdown document with front matter that can be used to sort the projects. How to do this is detailed here in [Hugo's documentation.](https://gohugo.io/content-management/types/)

**Comment by Allen616** [comment]
This will be part of Version 2 milestone for the website.
