### ISSUE TITLE
Add a sponsors page

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/website#38]
Bugsnag would like us to list them somewhere on our website as thanks for granting us their open source plan. Do we have a spot to do this?

**Comment by Allen616** [comment]
It has been on my event horizon. I guess that time is now.

**Comment by jacebrowning** [comment]
We could also add each of these: https://github.com/citizenlabsgr/homepage-legacy/issues?utf8=%E2%9C%93&q=is%3Aissue+sponsor+logo

**Comment by Allen616** [comment]
Do you have an estimate for the annual value of their sponsorship?

**Comment by jacebrowning** [comment]
Based on their cheapest team plan, I'd say $324/year.

**Comment by Allen616** [comment]
Working a dual path, an initial simple page and a more complicated version for long term. I am having difficulty integrating a nested menu for subpages,  to be used for the sponsor page.
