### ISSUE TITLE
social media links

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/website#56]
Correct so that social media logos appear in footer.

**Comment by Allen616** [comment]
The original theme used an older version of FontAwesome which did not include logos like meetup and GitHub, something we would like to include. While trying to update, I instead created an issue so that none of the logos now appear.

[FontAwesome, upgrading from Version 4](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)

**Comment by Allen616** [comment]
The following places are where I am trying to troubleshoot:

- static/css/icons.css
- layouts/partials/footer.html

config.yaml is the file that social media links and icons are provided for the site build.

**Comment by diiq** [comment]
Commit https://github.com/citizenlabsgr/website/commit/60a10191abc0e281cf215d6871b35bcded9a909f should fix this issue. @Allen616 your instincts were good, I added `fab` and also an `fa-` prefix to the class of each of the icons, and that seems to have done the trick.

**Comment by Allen616** [comment]
Great, thanks.

**Comment by jacebrowning** [comment]
Seems to be working:

![](https://zappy.zapier.com/3d01c53483deec8a5efd1b5e586cf89d.png)

**Comment by Allen616** [comment]
Does the css still need to be fixed (compiled??). I pushed the changes, but the site doesn’t look good on my iPad or phone.  I don’t know how to do that. @diiq
